feat: Create the online ingestion role
tecton-ai-ext/tecton-terraform-setup pull request #65
Opened 2022-12-01 05:08 UTC by achals

Signed-off-by: Achal Shah <achals@gmail.com>

As title, we need a new role that's s used by the online ingestion API. This will further need to be provided to Tecton for  cluster set up.

2022-12-01 05:09 UTC, achals commented
@scottames would really appreciate your eyeballs on this.

2022-12-01 16:44 UTC, scottames requested changes

2022-12-01 16:44 UTC, scottames commented on roles/roles.tf
> +// VPC - create, describe, delete network interfaces and write permissions to CloudWatch Logs.
```suggestion
/*
Needed for Lambda to talk to Redis
From AWS Docs : Provides minimum permissions for a Lambda function to execute while accessing a resource within a
VPC - create, describe, delete network interfaces and write permissions to CloudWatch Logs.
*/
```

2022-12-01 16:44 UTC, scottames commented on roles/roles.tf
> +#TODO: This should be templated, and the resources it has access to should be constrained.
This shouldn't be merged until both of these TODOs are resolved.

2022-12-01 16:44 UTC, scottames commented on roles/roles.tf
> +      # These permissions are used for orchestrator to discover which stream we publish offline log messages to.
```suggestion
      # Used by Tecton orchestration to discover which stream to publish offline log messages to
```

2022-12-01 16:44 UTC, scottames commented on roles/roles.tf
> +  name   = "tecton-${var.deployment_name}-online-ingestion"
Can this name be reduced? Many customers will hit the character limit.

2022-12-01 16:44 UTC, scottames commented on roles/roles.tf
> +  name   = "tecton-${var.deployment_name}-online-ingestion-management"
Can this name be reduced? Many customers will hit the character limit.

2022-12-01 16:44 UTC, scottames commented on roles/variables.tf
>  }
newline

2022-12-01 18:29 UTC, achals commented on roles/roles.tf
> +  name   = "tecton-${var.deployment_name}-online-ingestion-logs"
I'll try

2022-12-01 23:08 UTC, poojabhat0 commented on roles/roles.tf
> +data "template_file" "online_ingestion_management_policy_json" {
*ingest

2022-12-01 23:08 UTC, poojabhat0 submitted a review, later dismissed

2022-12-02 00:07 UTC, scottames commented on roles/roles.tf
> +data "template_file" "online_ingestion_management_policy_json" {
Should all of the other `ingestion` be `ingest`?

2022-12-02 18:03 UTC, scottames submitted a review, later dismissed

2022-12-02 18:07 UTC, scottames approved these changes

2022-12-02 18:07 UTC, merged