Add dummy policy and fargate service account role.
tecton-ai-ext/tecton-terraform-setup pull request #73
Opened 2022-12-09 17:41 UTC by kevjumba

Branched off of https://github.com/tecton-ai-ext/tecton-terraform-setup/pull/72. Adds the dummy role so that we can add a policy to it when we apply our terraform. 

[Decisions](https://docs.google.com/document/d/16OItHy4D6C9jzvjmxX0jv_4Wqs0ROsXQPj3EvBMf8bM/edit)

2022-12-13 00:03 UTC, scottames requested changes

2022-12-13 00:03 UTC, scottames commented on templates/fargate_eks_role.json
> +          "cloudwatch:PutMetricData"
```suggestion
            "cloudwatch:ListMetrics",
            "cloudwatch:PutMetricData"
```

2022-12-13 00:03 UTC, scottames commented on templates/fargate_eks_role.json
> +        "Sid": "AmazonS3Roles",
Can you match this sid with what it is in the EKS role? Likely something like, ReadWriteTectonBucket or something like that.

2022-12-13 00:03 UTC, scottames commented on templates/fargate_eks_role.json
> +        "Resource": "*"
Can this be reduced? At least using a tag conditional?

2022-12-14 00:50 UTC, kevjumba commented on templates/devops_fargate.json
> +                            "arn:aws:iam::*:policy/tecton-${DEPLOYMENT_NAME}-eks-fargate-node-policy"
Updated

2023-01-04 01:11 UTC, yan-lgtm commented on templates/fargate_eks_role.json
> +            "ecr:BatchGetImage"
What are these for?

2023-01-04 19:52 UTC, kevjumba commented on templates/fargate_eks_role.json
> +            "ecr:BatchGetImage"
This is just for getting the docker image that we are using to build the image. We just listed them out. They are essentially `AmazonEC2ContainerRegistryReadOnly`

2023-01-04 21:40 UTC, yan-lgtm reviewed
A few nits, I want to be super cautious on the stuff going to customer's repro.

2023-01-04 21:40 UTC, yan-lgtm commented on roles/roles.tf
> +
extra empty line here?

2023-01-04 21:40 UTC, yan-lgtm commented on roles/roles.tf
> +
One more extra line?

2023-01-04 21:40 UTC, yan-lgtm commented on roles/roles.tf
> +
extra line?

2023-01-04 21:40 UTC, yan-lgtm commented on templates/fargate_eks_role.json
> +            "ecr:BatchGetImage"
Okay can you add a comment to each of the role here? I think one is AmazonEC2ContainerRegistryReadOnly, and the others are [AmazonDynamoDBFullAccess] and [AmazonS3FullAccess]. What are the cloudwatchRoles for?

2023-01-04 22:08 UTC, kevjumba commented on templates/fargate_eks_role.json
> +            "ecr:BatchGetImage"
I can't add comments in json but I updated the name of the policy/action to be more meaningful. Let me know if you would like some more details.

2023-01-04 22:08 UTC, kevjumba commented on templates/fargate_eks_role.json
> +            "ecr:BatchGetImage"
I removed the cloudwatch roles, I don't think those are necessary anymore.

2023-01-04 22:15 UTC, yan-lgtm approved these changes
LGTM, I will have @scottames to take another look.

2023-01-09 18:48 UTC, scottames commented on emr_sample/infrastructure.tf
> +
This should be in the `databricks_sample` as well, no?

2023-01-09 18:50 UTC, scottames commented on roles/roles.tf
> +}
nit: can you put this up near line 81 with the template_file? Unless there's a good reason to put it at the end of the file?

2023-01-09 19:07 UTC, scottames commented on templates/fargate_eks_role.json
> +          "arn:aws:ecr:${REGION}:${ACCOUNT_ID}:tecton/*"
I think this should be the tecton account-id. The registries are owned by Tecton, no?

2023-01-09 23:24 UTC, kevjumba commented on roles/roles.tf
> +}
This is the policy document for the kinesis firehose, not the eks fargate dev ops role. Both need access.

2023-01-09 23:26 UTC, kevjumba commented on roles/roles.tf
> +}
done

2023-01-09 23:30 UTC, kevjumba commented on templates/fargate_eks_role.json
> +          "arn:aws:ecr:${REGION}:${ACCOUNT_ID}:tecton/*"
Yes, Thanks for the catch.

2023-01-11 21:54 UTC, scottames requested changes

2023-01-11 21:54 UTC, scottames commented on templates/fargate_eks_role.json
> +          "arn:aws:ecr:${REGION}:${ASSUMING_ACCOUNT_ID}:tecton/*"
Is region always going to be correct here? Should this be the region the deployment is in or the region the ECR registry lives in?

2023-01-11 21:54 UTC, scottames commented on templates/devops_fargate.json
> +                "arn:aws:iam::${ACCOUNT_ID}:oidc-provider/*"
Can this be scoped further by name or by tags (add a conditional - see other policies for example)?

2023-01-12 21:36 UTC, kevjumba commented on templates/devops_fargate.json
> +                "arn:aws:iam::${ACCOUNT_ID}:oidc-provider/*"
Added a condition

2023-01-12 21:58 UTC, kevjumba commented on templates/fargate_eks_role.json
> +          "arn:aws:ecr:${REGION}:${ASSUMING_ACCOUNT_ID}:tecton/*"
I just changed it to `*` since the region doesn't make it less secure as long as we restrict by account and repository.

2023-01-13 21:24 UTC, scottames approved these changes

2023-01-13 22:07 UTC, merged