Add permission change for satellite cluster in customer repo
tecton-ai-ext/tecton-terraform-setup pull request #81
Opened 2023-02-01 00:39 UTC by yan-lgtm

What
Add permission changes in terraform repo for the customer who wants satellite region.

Why
Help user to generate the permission changes easily

Same PR as https://github.com/tecton-ai/tecton/pull/5980

2023-02-07 21:32 UTC, zhoujoetan requested changes
The main feedback is to model the variables and resources assuming we can support a list of satellite regions.

2023-02-07 21:32 UTC, zhoujoetan commented on databricks_sample/infrastructure.tf
> +variable "satellite_region" {
Given that we assume there would be multiple satellite regions, could we model this variable after a list of regions (i.e. `satellite_regions`)? We can start with list with a single member.

2023-02-07 21:32 UTC, zhoujoetan commented on emr_sample/infrastructure.tf
> +variable "satellite_region" {
`satellite_region` -> `satellite_regions`

2023-02-07 21:32 UTC, zhoujoetan commented on roles/variables.tf
> +variable "satellite_region" {
`satellite_region` -> `satellite_regions`

2023-02-07 21:32 UTC, zhoujoetan commented on roles/roles.tf
> +  count      = var.fargate_enabled ? 1 : 0
```suggestion
  count  = var.fargate_enabled && var.satellite_region != "" ? 1 : 0
```

2023-02-08 19:08 UTC, rohita5l commented on databricks_sample/infrastructure.tf
> +variable "satellite_region" {
@yan-lgtm Whats the added overhead to do this. I want to weigh that against delivering this for Block asap.

2023-02-08 19:09 UTC, rohita5l commented on databricks_sample/infrastructure.tf
> +variable "satellite_region" {
specifically i mean adding support for multiple satellite clusters

2023-02-15 16:08 UTC, rohita5l commented on databricks_sample/infrastructure.tf
> +variable "fargate_enabled" {
How will rollout for this work with Block. In theory we will first work on Satellite cluster creation and then work on migrating their primary cluster to Fargate.
Is the plan that first they will set `satellite_regions ` but leave `fargate_enabled ` to false ? We then use it to create the satellite cluster and later migrate to Fargate ?
Can we do something where they set `satellite_regions ` and `fargate_enabled ` to true in the first pass. We use it to create a Fargate satellite cluster without changing anything in main cluster. Later on we migrate the main cluster ?

2023-02-15 16:22 UTC, yan-lgtm commented on databricks_sample/infrastructure.tf
> +variable "fargate_enabled" {
They set both to true and it won’t move their cluster to fargate. This only provision resources or give us permission to create resources. Fs pods are still on eks nodes.

2023-02-15 16:23 UTC, rohita5l commented on databricks_sample/infrastructure.tf
> +variable "fargate_enabled" {
okay makes sense. Im assuming plan is to create satellite cluster on fargate from the get go and later migrate existing cluster to fargate

2023-02-15 16:49 UTC, yan-lgtm commented on databricks_sample/infrastructure.tf
> +variable "fargate_enabled" {
Yes

2023-02-15 18:04 UTC, scottames requested changes
First pass.. let's VC about the `var.satellite_regions` -> `local.satellite_region` before moving forward.

2023-02-15 18:04 UTC, scottames commented on databricks_sample/infrastructure.tf
> +  satellite_region = split(",", var.satellite_regions)[0]
After looking over the PR further, I think we need to address this. Why are we talking in a string list comma separated and then splitting that into a single region, throwing away the rest?
Building on my previous comment, we should either A) say we only support 1 sat region today or B) give the customer a working example for one region, and document how to copy that module into more than one. (optimally we'd just use a for_each on the subnet & sg modules, but due to the provider limitation this is not possible.

2023-02-15 18:20 UTC, scottames commented on databricks_sample/infrastructure.tf
> +  satellite_region                = local.satellite_region
```suggestion
  satellite_regions                = local.satellite_regions
```

```hcl
# for each satellite.tf region, append to this list
locals { satellite_regions = ["us-east-1","us-west-2"] }
```

in roles:

```hcl
resource "iam_policy" "satellite" {
  for_each = toset(var.satellite_regions)

  name = "foo-${each.value}..."
```

2023-02-15 18:22 UTC, scottames commented on roles/roles.tf
> +  count    = var.satellite_region != "" ? 1 : 0
```suggestion
  for_each = toset(var.satellite_regions)
```

2023-02-15 18:22 UTC, scottames commented on roles/roles.tf
> +    REGION           = var.region
```suggestion
    REGION           = each.value
```

2023-02-15 18:27 UTC, scottames commented on templates/satellite_devops_policy.json
> +            ]
Move list to template file generation in .tf file

```hcl
[ for region in var.satellite_regions :
                "arn:aws:elasticloadbalancing:${region}:${ACCOUNT_ID}:listener/net/tecton-${DEPLOYMENT_NAME}*",
                "arn:aws:elasticloadbalancing:${region}:${ACCOUNT_ID}:listener/app/tecton-${DEPLOYMENT_NAME}*",
                "arn:aws:elasticloadbalancing:${region}:${ACCOUNT_ID}:loadbalancer/net/${DEPLOYMENT_NAME_CONCAT}*",
                "arn:aws:elasticloadbalancing:${region}:${ACCOUNT_ID}:loadbalancer/app/${DEPLOYMENT_NAME_CONCAT}*",
                "arn:aws:elasticloadbalancing:${region}:${ACCOUNT_ID}:targetgroup/tecton-${var.deployment_name}*",
                "arn:aws:autoscaling:${region}:${ACCOUNT_ID}:autoScalingGroup::autoScalingGroupName/tecton-${DEPLOYMENT_NAME}*",
                "arn:aws:autoscaling:${region}:${var.account_id}:autoScalingGroup:*:autoScalingGroupName/eks-*"
            ]
```

2023-02-15 18:28 UTC, scottames commented on templates/satellite_devops_policy.json
> +            ]
Or start w/ `*` for the region to KISS and we'll do this if the customer pushes back.

2023-02-15 18:32 UTC, scottames requested changes
Next steps:

1. Move satellite changes from `databricks_sample/infrastructure.tf` to `databricks_sample/satellite.tf`
    1. Illustrate 1 provider + subnets module + security group module per region
    2. The customer can then copy this & make unique when they add more regions (down the road)
1. Modify the roles module to take in `var.sat_regions` as a list of regions while documenting that the customer should add each sat region they create to this list
    1. the roles module will then 
        1. use for_each on policies/roles for EKS resources to create one per sat cluster
        2. use `*` or list comprehension to add to existing devops policy rather than creating one policy per region

2023-02-15 18:36 UTC, scottames commented on databricks_sample/infrastructure.tf
> +  satellite_region = split(",", var.satellite_regions)[0]
After discussing, see next steps in follow-up comment. Thanks @yan-lgtm !

2023-02-15 18:37 UTC, scottames commented on roles/roles.tf
> +  fargate_satellite_kinesis_delivery_stream_arn = "arn:aws:firehose:${var.satellite_region}:${var.account_id}:deliverystream/tecton-${var.deployment_name}-fargate-log-delivery-stream"
This is similar to the [other comment below](https://github.com/tecton-ai-ext/tecton-terraform-setup/pull/81#discussion_r1107537258). Address this in the same way if it makes sense.

2023-02-15 21:18 UTC, yan-lgtm commented on databricks_sample/infrastructure.tf
> +  default     = false
yes, it's going to be for all regions

2023-02-16 18:20 UTC, yan-lgtm commented on databricks_sample/satellite.tf
> +  satellite_region = length(var.satellite_regions) > 0 ? var.satellite_regions[0] : var.region
We have to get a region for the satellite provider.

2023-02-21 17:21 UTC, scottames requested changes

2023-02-21 17:21 UTC, scottames commented on roles/roles.tf
> +        [for region in var.satellite_regions: aws_iam_policy.eks_fargate_satellite_node_policy[region].arn]
same here, formatlist is cleaner. But nicely done with the for_each in the policy!

2023-02-21 17:21 UTC, scottames commented on roles/roles.tf
> +##### Below are all the resources brought up for satellite cluster #####
```suggestion
##### Satellite cluster #####
```
Does it make sense to just put this in a separate `satellite.tf` file?

2023-02-21 17:21 UTC, scottames commented on roles/roles.tf
> +locals {
How are these locals different from the locals at the top? You have satellite references in those. Super confusing.

2023-02-21 17:21 UTC, scottames commented on roles/roles.tf
> +  satellite_dynamo_tables = [
formatlist is cleaner, if you change the others change this one too.

2023-02-21 17:21 UTC, scottames commented on roles/roles.tf
> +    ["arn:aws:dynamodb:${var.region}:${var.account_id}:table/tecton-${var.deployment_name}*"]
I thought we decided that going with `*` for the region was the approach we would take for now?

It's much simpler (adds less noise) and will keep us from hitting the policy character limit.

2023-02-21 17:21 UTC, scottames commented on roles/roles.tf
> +  count    = length(var.satellite_regions) > 0 ? 1 : 0
Change `length(var.satellite_regions) > 0` to the same sort of local, `is_satellite_regions_enabled`

2023-02-21 17:21 UTC, scottames commented on roles/roles.tf
> +  role       = aws_iam_role.eks_node_role.name
There should be separate roles for each satellite cluster. Each EKS cluster should not reuse the other clusters' roles. The policies can be reused, not the roles.

2023-02-21 17:21 UTC, scottames commented on roles/roles.tf
> +  name   = "tecton-${var.deployment_name}-${each.key}-eks-fargate-node-policy"
This name is likely to hit the character limit.
```suggestion
  name   = "tecton-${var.deployment_name}-${each.key}-eks-fargate"
```

2023-02-21 17:21 UTC, scottames commented on roles/roles.tf
> +resource "aws_iam_policy" "eks_fargate_satellite_node_policy" {
```suggestion
resource "aws_iam_policy" "eks_fargate_satellite_node" {
```

2023-02-21 17:21 UTC, scottames commented on roles/roles.tf
> +# DEVOPS [Common : Databricks and EMR]
Is there a reason we need to create more policies for the DevOps role? Can we not just append or update (e.g. region -> `*`) to the existing?

2023-02-21 17:21 UTC, scottames commented on roles/roles.tf
> +  name   = "tecton-${var.deployment_name}-${each.key}-fargate-satellite-logging-to-kinesis-firehose"
Are you confident this name won't quickly hit the character limit?

2023-02-21 17:21 UTC, scottames commented on roles/variables.tf
> +  description = "The satellite region for Tecton deployment."
```suggestion
  description = "The satellite regions for Tecton deployment. Only enable this if instructed to by Tecton support."
```

2023-02-21 17:21 UTC, scottames commented on templates/devops_fargate.json
> +                "arn:aws:eks:*:${ACCOUNT_ID}:fargateprofile/tecton-${DEPLOYMENT_NAME}*"
👍🏻

2023-02-21 17:21 UTC, scottames commented on templates/satellite_ca_policy.json
> +            "Resource": ${SATELLITE_DYNAMO_TABLES}
Why are global and satellite separate?

2023-02-21 17:21 UTC, scottames commented on roles/roles.tf
> +    GLOBAL_DYNAMO_TBLES     = jsonencode(local.global_dynamo_tables)
Spelling. `GLOBAL_DYNAMO_TABLES`

2023-02-21 18:56 UTC, yan-lgtm commented on databricks_sample/satellite.tf
> +  vpc_id                          = module.subnets.vpc_id
good catch, dev-emr-vpc is on emr so I applied on the emr_sample

2023-02-21 19:48 UTC, yan-lgtm commented on templates/satellite_ca_policy.json
> +            "Resource": ${SATELLITE_DYNAMO_TABLES}
These are just for satellite replicas?

2023-02-21 19:53 UTC, yan-lgtm commented on roles/roles.tf
> +##### Below are all the resources brought up for satellite cluster #####
I thought we discussed this offline, and it was ok to keep them in the same file. Do you want me to split into new file?

2023-02-21 19:54 UTC, yan-lgtm commented on roles/roles.tf
> +locals {
these are the locals for the satellite cluster?

2023-02-21 20:06 UTC, yan-lgtm commented on roles/roles.tf
> +  role       = aws_iam_role.eks_node_role.name
This is for the worker role to write to replica in satellite region, not for the feature server role to retrieve right?

2023-02-21 20:15 UTC, yan-lgtm commented on roles/roles.tf
> +# DEVOPS [Common : Databricks and EMR]
Security groups are `*` in the naming so we want to restrict them to region?

2023-02-21 20:31 UTC, yan-lgtm commented on roles/roles.tf
> +resource "aws_iam_policy" "eks_fargate_satellite_node_policy" {
I assume you don't want me to change every policy in this file right? as some of the policies contain the `_policy` suffix

2023-02-21 22:07 UTC, yan-lgtm commented on roles/roles.tf
> +  name   = "tecton-${var.deployment_name}-${each.key}-fargate-satellite-logging-to-kinesis-firehose"
Reduced chars

2023-02-21 23:27 UTC, scottames commented on emr_sample/satellite.tf
> +module "eks_satellite_subnets" {
It's probably worth making a note that we do not run EMR in the satellite regions, just the feature serving. (right?) I can see it being somewhat confusing that we're not setting up subnets, etc. for EMR here.

2023-02-21 23:27 UTC, scottames commented on roles/roles.tf
> +  satellite_feature_server_roles = formatlist("arn:aws:iam::${var.account_id}:role/tecton-${var.deployment_name}-%s-fargate-fs", var.satellite_regions)
```suggestion
  satellite_feature_server_roles = formatlist("arn:aws:iam::%s:role/tecton-%s-%s-fargate-fs", var.account_id, var.deployment_name, var.satellite_regions)
```

2023-02-21 23:27 UTC, scottames commented on roles/roles.tf
> +    formatlist("arn:aws:s3:::tecton-${var.deployment_name}-%s", var.satellite_regions),
```suggestion
    formatlist("arn:aws:s3:::tecton-%s-%s", var.deployment_name, var.satellite_regions),
```

2023-02-21 23:27 UTC, scottames commented on roles/roles.tf
> +        [for region in var.satellite_regions: aws_iam_policy.eks_fargate_satellite_node_policy[region].arn]
Sorry, apparently I had something else in mind when I made that comment.

2023-02-21 23:27 UTC, scottames commented on roles/roles.tf
> +  s3_objects = formatlist("%s/*", local.s3_buckets)
In all of these locals & the policies/roles where they end up, what happens if `var.satellite_regions == []`? Do they all render correctly? 
For example, does another cluster w/o satellite region(s) enabled go unmodified? (other than maybe the `*` replacement for region)

2023-02-21 23:27 UTC, scottames commented on roles/roles.tf
> +  s3_objects = formatlist("%s/*", local.s3_buckets)
If you're unsure. How do you plan on testing this case?

2023-02-21 23:27 UTC, scottames commented on roles/roles.tf
> +locals {
I see what you're saying. You still have `local.satellite_feature_server_roles` in the other file. Should that (and any others?) move to the satellite.tf/locals?

2023-02-21 23:27 UTC, scottames commented on templates/devops_eks_policy.json
> +                "arn:aws:eks:*:${ACCOUNT_ID}:nodegroup/${DEPLOYMENT_NAME}*"
Why these additions?

2023-02-21 23:27 UTC, scottames commented on roles/roles.tf
> +  role       = aws_iam_role.eks_node_role.name
Sorry for the confusion. I'll make a new comment.

2023-02-21 23:27 UTC, scottames commented on roles/roles.tf
> +resource "aws_iam_policy" "eks_fargate_satellite_node_policy" {
the `_policy` is overly redundant IMO and makes the terraform harder to read. If it's easy to clean it up, be my guest. It's okay if you don't though.

2023-02-21 23:27 UTC, scottames commented on roles/satellite.tf
> +  name   = "tecton-${var.deployment_name}-${each.key}-eks-fargate"
```suggestion
  name   = "tecton-${var.deployment_name}-${each.key}-eks-fargate-node"
```
sorry.. my suggestion killed too much of the name. I think it'd probably be fine, but has the tendency to collide with other names.

2023-02-21 23:27 UTC, scottames commented on roles/roles.tf
> +# DEVOPS [Common : Databricks and EMR]
Got it. Thank you. How close does this put us to hitting the max policies? (10)

2023-02-21 23:27 UTC, scottames commented on templates/satellite_ca_policy.json
> +            "Resource": ${SATELLITE_DYNAMO_TABLES}
Got it. Thank you.

2023-02-21 23:29 UTC, scottames requested changes

2023-02-21 23:29 UTC, scottames commented on roles/satellite.tf
> +}
You're standing up a new EKS cluster in the satellite region, no? What management & node IAM roles are you using for that cluster? I don't see anywhere here where you're creating new roles for them.

2023-02-22 00:30 UTC, yan-lgtm commented on roles/roles.tf
> +  s3_objects = formatlist("%s/*", local.s3_buckets)
my plan was that should stays the same, but with the region change to `*` there are diffs for sure. What do you recommend? Changing to `*` is ok or i should add an if before every corner case?

2023-02-22 00:38 UTC, yan-lgtm commented on roles/satellite.tf
> +}
Management role is using the same AWS managed permission, right? Does it make sense to create a new one, with a diff name?

2023-02-22 00:39 UTC, scottames commented on roles/roles.tf
> +  s3_objects = formatlist("%s/*", local.s3_buckets)
The changes to `*` are fine.  I'm more concerned about the rest of the policies. How will including the satellite locals into the mix affect things if satellite is not enabled?

2023-02-22 00:45 UTC, scottames commented on roles/satellite.tf
> +}
The node roles should be separate, for sure. I could be convinced to reuse the management role, but I think it would make sense to separate them both if we're separating. It's best practice really.

2023-02-22 07:17 UTC, yan-lgtm commented on roles/roles.tf
> +  s3_objects = formatlist("%s/*", local.s3_buckets)
To sum it up here, I don't think if `var.satellite_regions == []` will have any impacts. Looking at all the policies, we only changed devops_eks_policy, devops_eks_vpc_endpoint, devops_policy_1, and devops_policy_2. All of the changes are from `region` to `*`, except the S3 path, and we can easily confirm here is no satellite_region is defined, S3 path stays the same as `"arn:aws:s3:::tecton-${DEPLOYMENT_NAME}"`. If we are ok with changes to `*`, i don't think there will be any risks.

2023-02-22 07:22 UTC, yan-lgtm commented on roles/roles.tf
> +locals {
well that's for the devops policy, and i want to make that variable closer to where it is supposed use so less confusion on where the variable is?

2023-02-22 07:24 UTC, yan-lgtm commented on roles/roles.tf
> +# DEVOPS [Common : Databricks and EMR]
I think we still have roughly 3 left

2023-02-22 19:33 UTC, yan-lgtm commented on roles/roles.tf
> +resource "aws_iam_policy" "eks_fargate_satellite_node_policy" {
I want to be your guest but looks like changing the name will incurr everything recreated. Sorry I can't do that.

2023-02-22 21:38 UTC, scottames commented on emr_sample/satellite.tf
> +# Only feature serving related infrastructer is brought up in the satellite region. We will not create EMR subnets in the satellite region.
```suggestion
# Only feature serving related infrastructure is brought up in the satellite region. EMR networking will not be created in the satellite region.
```

2023-02-22 21:38 UTC, scottames commented on roles/roles.tf
> +  s3_objects = formatlist("%s/*", local.s3_buckets)
Thanks for verifying this.

2023-02-22 21:43 UTC, scottames approved these changes
One small change to the spelling/wording in your comment

2023-02-23 16:03 UTC, scottames approved these changes

2023-02-23 17:07 UTC, merged