add satellite replication policy
tecton-ai-ext/tecton-terraform-setup pull request #95
Opened 2023-04-14 22:11 UTC by yan-lgtm

2023-04-18 23:59 UTC, scottames requested changes

2023-04-18 23:59 UTC, scottames commented on roles/satellite.tf
> +resource "aws_iam_policy" "replication" {
```suggestion
resource "aws_iam_policy" "s3_replication" {
```

2023-04-18 23:59 UTC, scottames commented on roles/satellite.tf
> +data "aws_iam_policy_document" "replication_policy" {
```suggestion
data "aws_iam_policy_document" "s3_replication_policy" {
```

2023-04-18 23:59 UTC, scottames commented on roles/satellite.tf
> +  name   = "tecton-s3-bucket-replication-${var.deployment_name}"
I think you changed a bunch of names in the internal PR that don't match here (and elsewhere in this PR) - can you verify & test it?

2023-04-19 00:22 UTC, yan-lgtm commented on roles/satellite.tf
> +  name   = "tecton-s3-bucket-replication-${var.deployment_name}"
This would probably be fine, as these are the policy names. As long as the iam role name matches https://github.com/tecton-ai-ext/tecton-terraform-setup/pull/95/files#diff-28bb7e9d8bcdcf9471dc18877a49ab16192289c6a93afc3feffad66f8309eea7R20-R21 we should be fine.
I also tested locally.

2023-04-20 17:16 UTC, scottames approved these changes

2023-04-20 17:20 UTC, merged