Policy for data validation worker running on Fargate
tecton-ai-ext/tecton-terraform-setup pull request #96
Opened 2023-04-21 19:09 UTC by pyalex

For VPC deployments similarly to the feature server policy we want to have a separate policy for data validation workers that also will be hosted on Fargate.

This policy is created when the flag `data_validation_on_fargate_enabled` is set to `true`. However, in order to use Fargate we also need "pod_execution_role" to be created. Hence `data_validation_on_fargate_enabled` should be switched on together with `fargate_enabled`.

2023-04-21 20:31 UTC, scottames requested changes
A couple small nits. Primarily, can we namespace the outputs with the other "fargate" outputs?

@yan-lgtm @kevjumba mind double checking me?

2023-04-21 20:31 UTC, scottames commented on emr_sample/outputs.tf
> +    eks_fargate_data_validation_worker_policy_name  = (var.apply_layer > 1) ? module.roles[0].eks_fargate_data_validation_worker_policy_name : ""
```suggestion
    fargate_data_validation_worker_policy_name  = (var.apply_layer > 1) ? module.roles[0].eks_fargate_data_validation_worker_policy_name : ""
```

2023-04-21 20:31 UTC, scottames commented on roles/outputs.tf
> +output "eks_fargate_data_validation_worker_policy_name" {
```suggestion
output "fargate_data_validation_worker_policy_name" {
```

2023-04-21 20:31 UTC, scottames commented on roles/variables.tf
> +}
```suggestion
}

```

2023-04-21 20:31 UTC, scottames commented on templates/data_validation_worker_policy.json
> +}
```suggestion
}

```

2023-04-21 20:38 UTC, yan-lgtm commented on roles/roles.tf
> +  count = (var.fargate_enabled && var.data_validation_on_fargate_enabled) ? 1 : 0
can you move `(var.fargate_enabled && var.data_validation_on_fargate_enabled)` into a variable so you can reuse?

2023-04-21 20:38 UTC, yan-lgtm commented on roles/roles.tf
> +resource "aws_iam_policy" "eks_fargate_data_validation_worker_policy" {
this is called aws_iam_policy already, can you rename this to "eks_fargate_data_validation_worker"

2023-04-21 20:38 UTC, yan-lgtm commented on templates/data_validation_worker_policy.json
> +      "Sid": "ReadWriteDataMetricsPolicies",
This is for dynamodb, do you need this for your role?

2023-04-21 20:38 UTC, yan-lgtm commented on databricks_sample/infrastructure.tf
> +  data_validation_on_fargate_enabled = var.data_validation_on_fargate_enabled
Can you add extra spaces from line 113-123?

2023-04-21 21:43 UTC, pyalex commented on templates/data_validation_worker_policy.json
> +      "Sid": "ReadWriteDataMetricsPolicies",
Yes, data metrics are stored in Dynamo.

2023-04-21 21:43 UTC, pyalex commented on templates/data_validation_worker_policy.json
> +      "Sid": "ReadWriteDataMetricsPolicies",
We read and write metrics for validation workers.

2023-04-21 21:53 UTC, pyalex commented on roles/roles.tf
> +  count = (var.fargate_enabled && var.data_validation_on_fargate_enabled) ? 1 : 0
Added to locals

2023-04-21 21:55 UTC, pyalex commented on databricks_sample/infrastructure.tf
> +  data_validation_on_fargate_enabled = var.data_validation_on_fargate_enabled
fomatted

2023-04-21 21:57 UTC, yan-lgtm approved these changes

2023-04-21 21:57 UTC, yan-lgtm commented on databricks_sample/outputs.tf
> +    fargate_data_validation_worker_policy_name = module.roles.fargate_data_validation_worker_policy_name
Can you also format here?

2023-04-21 21:59 UTC, pyalex commented on databricks_sample/outputs.tf
> +    fargate_data_validation_worker_policy_name = module.roles.fargate_data_validation_worker_policy_name
Done

2023-04-21 22:03 UTC, yan-lgtm approved these changes

2023-04-24 17:23 UTC, scottames approved these changes

2023-04-24 19:40 UTC, merged